/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VariablesIndexRouteImport } from './routes/variables/index'
import { Route as TilesIndexRouteImport } from './routes/tiles/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as VariablesVariableTypeRouteImport } from './routes/variables/$variableType'
import { Route as TilesTileIdRouteImport } from './routes/tiles/$tileId'
import { Route as TemplatesTemplateIdRouteImport } from './routes/templates/$templateId'
import { Route as ComponentsComponentIdRouteImport } from './routes/components/$componentId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesIndexRoute = VariablesIndexRouteImport.update({
  id: '/variables/',
  path: '/variables/',
  getParentRoute: () => rootRouteImport,
} as any)
const TilesIndexRoute = TilesIndexRouteImport.update({
  id: '/tiles/',
  path: '/tiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const VariablesVariableTypeRoute = VariablesVariableTypeRouteImport.update({
  id: '/variables/$variableType',
  path: '/variables/$variableType',
  getParentRoute: () => rootRouteImport,
} as any)
const TilesTileIdRoute = TilesTileIdRouteImport.update({
  id: '/tiles/$tileId',
  path: '/tiles/$tileId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesTemplateIdRoute = TemplatesTemplateIdRouteImport.update({
  id: '/templates/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsComponentIdRoute = ComponentsComponentIdRouteImport.update({
  id: '/components/$componentId',
  path: '/components/$componentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tiles/$tileId': typeof TilesTileIdRoute
  '/variables/$variableType': typeof VariablesVariableTypeRoute
  '/components': typeof ComponentsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/tiles': typeof TilesIndexRoute
  '/variables': typeof VariablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tiles/$tileId': typeof TilesTileIdRoute
  '/variables/$variableType': typeof VariablesVariableTypeRoute
  '/components': typeof ComponentsIndexRoute
  '/templates': typeof TemplatesIndexRoute
  '/tiles': typeof TilesIndexRoute
  '/variables': typeof VariablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/components/$componentId': typeof ComponentsComponentIdRoute
  '/templates/$templateId': typeof TemplatesTemplateIdRoute
  '/tiles/$tileId': typeof TilesTileIdRoute
  '/variables/$variableType': typeof VariablesVariableTypeRoute
  '/components/': typeof ComponentsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
  '/tiles/': typeof TilesIndexRoute
  '/variables/': typeof VariablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/components/$componentId'
    | '/templates/$templateId'
    | '/tiles/$tileId'
    | '/variables/$variableType'
    | '/components'
    | '/templates'
    | '/tiles'
    | '/variables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/components/$componentId'
    | '/templates/$templateId'
    | '/tiles/$tileId'
    | '/variables/$variableType'
    | '/components'
    | '/templates'
    | '/tiles'
    | '/variables'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/components/$componentId'
    | '/templates/$templateId'
    | '/tiles/$tileId'
    | '/variables/$variableType'
    | '/components/'
    | '/templates/'
    | '/tiles/'
    | '/variables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComponentsComponentIdRoute: typeof ComponentsComponentIdRoute
  TemplatesTemplateIdRoute: typeof TemplatesTemplateIdRoute
  TilesTileIdRoute: typeof TilesTileIdRoute
  VariablesVariableTypeRoute: typeof VariablesVariableTypeRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
  TilesIndexRoute: typeof TilesIndexRoute
  VariablesIndexRoute: typeof VariablesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables/': {
      id: '/variables/'
      path: '/variables'
      fullPath: '/variables'
      preLoaderRoute: typeof VariablesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiles/': {
      id: '/tiles/'
      path: '/tiles'
      fullPath: '/tiles'
      preLoaderRoute: typeof TilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/variables/$variableType': {
      id: '/variables/$variableType'
      path: '/variables/$variableType'
      fullPath: '/variables/$variableType'
      preLoaderRoute: typeof VariablesVariableTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiles/$tileId': {
      id: '/tiles/$tileId'
      path: '/tiles/$tileId'
      fullPath: '/tiles/$tileId'
      preLoaderRoute: typeof TilesTileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$templateId': {
      id: '/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof TemplatesTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/$componentId': {
      id: '/components/$componentId'
      path: '/components/$componentId'
      fullPath: '/components/$componentId'
      preLoaderRoute: typeof ComponentsComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComponentsComponentIdRoute: ComponentsComponentIdRoute,
  TemplatesTemplateIdRoute: TemplatesTemplateIdRoute,
  TilesTileIdRoute: TilesTileIdRoute,
  VariablesVariableTypeRoute: VariablesVariableTypeRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
  TilesIndexRoute: TilesIndexRoute,
  VariablesIndexRoute: VariablesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
